### ISSUE TITLE
Fatal error on a big file

### ISSUE THREAD

**Issue by asr** [gilith/metis#1]
Running Metis on a *50 MB* file from [TPTP](http://www.cs.miami.edu/~tptp/) 6.4.0, I got the following fatal error:

```
$ cd TPTP/Axioms
$ metis MED002+0.ax

FATAL ERROR: metis failed:
error in TPTP file "MED002+0.ax" around line 1705619:
    mesh__activeMeSHYear(mesh__D007174,'2003') )).

%------------------------------------------------------------------------------
EOF inside a block comment
```

I could process the above file using other ATPs.

Version:
```
$ metis --version
metis 2.3 (release 20160714)
```

CC'ing @jonaprieto.

**Comment by gilith** [comment]
Thanks for the bug report, the root cause was a quote containing a block comment opener */ that wasn't being handled properly. The latest release

$ metis --version
metis 2.3 (release 20161108)

which is pushed to this repo fixes the issue.

**Comment by asr** [comment]
Thanks for fixing the issue and the release.
