### ISSUE TITLE
Ordered paramodulation vs. superposition

### ISSUE THREAD

**Issue by blanchette** [gilith/metis#12]
Metis appears to implement the ordered paramodulation calculus. In the AR community, superposition, with its extra ordering restriction, is widely considered as a more efficient calculus. It is the calculus of E, SPASS, Vampire, Zipperposition, etc.

Is there a particular reason why Metis doesn't implement superposition?

If we were to provide a patch to perform superposition, would you potentially be interested in applying it upstream?

Jasmin & Martin

**Comment by gilith** [comment]
I remember reading some papers on superposition when I was implementing Metis, but I can't recall the reasons that I settled on ordered paramodulation.

Unfortunately, at the moment I only have the bandwidth to maintain Metis in its current form (that I understand), so I would only be interested in applying a superposition patch upstream if it was a small change. However, if you wanted to fork Metis and implement superposition with a view to integrating a more powerful prover into Isabelle then that would be fine with me.
