### ISSUE TITLE
FATAL ERROR: BUG found in metis program: Active.simplify

### ISSUE THREAD

**Issue by 01mf02** [gilith/metis#8]
[Here](https://github.com/gilith/metis/files/1390810/fc6d942dd6159bfb75a254d307291b164.txt) is one more problem that triggers a bug in Metis. The error message states:

    FATAL ERROR: BUG found in metis program:
    Active.simplify: clause should have been simplified away

**Comment by gilith** [comment]
Thanks Michael, I can reproduce the bug and am working to root-cause it.

**Comment by gilith** [comment]
I've root-caused the bug to some mishandling of disequalities during rewriting. For example, given the rewrite f X = c, the clause ~(f Y = g a b) \/ p (g a b) should be rewritten to ~(c = g a b) \/ p c in one step, but the buggy code caused the rewrite to return ~(c = g a b) \/ p (g a b). If this clause was rewritten again it would correctly return ~(c = g a b) \/ p c, but it shouldn't take two steps to do this.

I've released a new version - Metis 2.3 (release 20171021) - that fixes this and will shortly push a commit that closes this issue.

Thank you for the bug report, please keep them coming. You're up to two incompleteness bugs on the [changelog](http://www.gilith.com/software/metis/changelog.html) now :-)
